"""empty message

Revision ID: 007489477763
Revises: 243d793470cf
Create Date: 2020-10-18 02:46:58.158326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007489477763'
down_revision = '243d793470cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('description', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'description')
    # ### end Alembic commands ###
