"""empty message

Revision ID: 09f013c26c55
Revises: f60696b7a4c8
Create Date: 2020-07-15 23:47:12.904749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09f013c26c55'
down_revision = 'f60696b7a4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('user_profile', sa.Column('photoFsRef', sa.String(length=50), nullable=True))
    op.alter_column('user_profile', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('user_profile', 'photoFsRef')
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
