"""empty message

Revision ID: 0fb46dcd6b05
Revises: 740eb3fd3291
Create Date: 2020-07-25 23:04:41.848571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb46dcd6b05'
down_revision = '740eb3fd3291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prep_instruction', sa.Column('step_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prep_instruction', 'step_order')
    # ### end Alembic commands ###
