"""empty message

Revision ID: 243d793470cf
Revises: d42c9e794e4f
Create Date: 2020-08-16 01:42:10.090472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243d793470cf'
down_revision = 'd42c9e794e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
