"""empty message

Revision ID: 34906c256b91
Revises: 0fb46dcd6b05
Create Date: 2020-07-26 00:06:00.270203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34906c256b91'
down_revision = '0fb46dcd6b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('main_dish', sa.Integer(), nullable=True))
    op.drop_column('dish', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('dish', 'main_dish')
    # ### end Alembic commands ###
