"""empty message

Revision ID: 51e2d21e141c
Revises: ee688f226c36
Create Date: 2020-07-28 23:40:34.469563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e2d21e141c'
down_revision = 'ee688f226c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prep_instruction', sa.Column('main_dish', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prep_instruction', 'main_dish')
    # ### end Alembic commands ###
