"""add es_keywords field

Revision ID: 5d61ba9c4fc8
Revises: b718be435c37
Create Date: 2021-01-11 22:48:53.156807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d61ba9c4fc8'
down_revision = 'b718be435c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('es_keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'es_keywords')
    # ### end Alembic commands ###
