"""add status field on ingredients

Revision ID: 714f8c536d8f
Revises: 5e1bc4da11bc
Create Date: 2020-11-21 01:16:24.538373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714f8c536d8f'
down_revision = '5e1bc4da11bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'status')
    # ### end Alembic commands ###
