"""empty message

Revision ID: b1edb0f3afac
Revises: d42c9e794e4f
Create Date: 2020-08-09 18:35:23.232761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1edb0f3afac'
down_revision = 'd42c9e794e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=5), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('grocery_item_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=200), nullable=True),
    sa.Column('main_dish', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dish_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('ingredient_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('main_dish', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('step_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grocery_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], name='ingredients_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ingredient')
    # ### end Alembic commands ###
