"""add status field to PrepInstruction

Revision ID: b718be435c37
Revises: 714f8c536d8f
Create Date: 2020-12-10 14:48:44.854562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b718be435c37'
down_revision = '714f8c536d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prep_instruction', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prep_instruction', 'status')
    # ### end Alembic commands ###
