"""adding back description

Revision ID: cbb7c0ceb1e1
Revises: 007489477763
Create Date: 2020-10-19 01:22:37.430508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb7c0ceb1e1'
down_revision = '007489477763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'description')
    # ### end Alembic commands ###
