"""empty message

Revision ID: d25e4df83372
Revises: de82b3f7c5d3
Create Date: 2020-08-06 02:47:48.688212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25e4df83372'
down_revision = 'de82b3f7c5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('coverPhotoFsRef', sa.Text(), nullable=True))
    op.add_column('user_profile', sa.Column('tagline', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'tagline')
    op.drop_column('user_profile', 'coverPhotoFsRef')
    # ### end Alembic commands ###
