"""empty message

Revision ID: d42c9e794e4f
Revises: d25e4df83372
Create Date: 2020-08-09 16:54:09.016360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd42c9e794e4f'
down_revision = 'd25e4df83372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('grocery_item_id', sa.Integer(), nullable=True))
    op.alter_column('ingredients', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('ingredients', 'ingredient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('ingredient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('ingredients', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('ingredients', 'grocery_item_id')
    # ### end Alembic commands ###
