"""empty message

Revision ID: de82b3f7c5d3
Revises: 5d2e90dde0d8
Create Date: 2020-08-05 23:47:37.212571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de82b3f7c5d3'
down_revision = '5d2e90dde0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('country', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'country')
    # ### end Alembic commands ###
