"""empty message

Revision ID: ea11435b0271
Revises: 74e6671a2c4a
Create Date: 2020-07-18 01:51:13.872064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea11435b0271'
down_revision = '74e6671a2c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('short_bio', table_name='user_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('short_bio', 'user_profile', ['short_bio'], unique=True)
    # ### end Alembic commands ###
